base_url = "https://samyhaff.github.io"
title = "Samy Haffoudhi"
description = "My personal site"

compile_sass = true
build_search_index = false

theme = "serene"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
    { theme = "serene-light", filename = "hl-light.css"},
    { theme = "serene-dark", filename = "hl-dark.css"},
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

# [extra]
# after_dark_menu = [
#     {url = "$BASE_URL", name = "Home"},
#     {url = "$BASE_URL/about", name = "About"},
#     {url = "$BASE_URL/categories", name = "Categories"},
#     # {url = "$BASE_URL/tags", name = "Tags"},
#     {url = "https://github.com/samyhaff", name = "Github"},
#     # {url = "https://www.linkedin.com/in/samy-haffoudhi-112b8b164/", name = "LinkedIn"},
#     {url = "mailto:haffoudhisamy@gmail.com", name = "Contact"},
# ]
# author = "Samy"
# after_dark_title = "Samy Haffoudhi"

[extra]

name = "Samy"                         # Your name
id = "samyhaff"                           # Your id / username / handle
bio = "Welcome to my personal site :)"                          # Your bio
avatar = "img/avatar.jpeg"            # Your avatar
links = [                             # Your links
    { name = "GitHub", icon = "github", url = "https://github.com/<your-username>" },
    # { name = "Twitter", icon = "twitter", url = "https://twitter.com/<your-username>" },
    { name = "Email", icon = "email", url = "mailto:haffoudhisamy@gmail.com" },
]

homepage_layout = "about"             # "about" | "list" | "recent"

recent_max = 15
recent_more = true
recent_more_text = "more »"

sections = [
    { name = "blog", path = "/blog", is_external = false },
    # { name = "projects", path = "/projects", is_external = false },
    { name = "about", path = "/about", is_external = false },
    { name = "github", path = "https://github.com/samyhaff", is_external = true },
]
blog_section_path = "/blog"

nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

display_id = true                     # Whether to display your id on homepage
blog_categorized = true               # Whether to categorize blog posts
blur_effect = true                    # Whether to turn on blur effect on navigation bar
back_to_top = true                    # Whether to show back-to-top button on post pages

toc = true                            # Whether to show Table-Of-Contents by default
copy = true                           # Whether to add a copy button on code blocks by default
comment = false                       # Whether to show giscus comment section by default, see https://giscus.app for more info
display_tags = true                   # Whether to display tags on post pages by default
truncate_summary = false              # Whether to truncate the summary of a post by default

outdate_alert = false                 # Whether to show outdate alert by default
outdate_alert_days = 120              # How many days will a post be outdated by default
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

footer_copyright = "© 2023 <your-name>"
footer_credits = true                 # Whether to show "powered by zola and serene" in footer

not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"
