base_url = "https://samyhaff.github.io"
title = "Samy Haffoudhi"
description = "My personal site"

compile_sass = true
build_search_index = false

theme = "after-dark"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true

[extra]
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/categories", name = "Categories"},
    # {url = "$BASE_URL/tags", name = "Tags"},
    {url = "https://github.com/samyhaff", name = "Github"},
    # {url = "https://www.linkedin.com/in/samy-haffoudhi-112b8b164/", name = "LinkedIn"},
    {url = "mailto:haffoudhisamy@gmail.com", name = "Contact"},
]
author = "Samy"
after_dark_title = "Samy Haffoudhi"
